### ISSUE TITLE
Low-level hardware failure in specific computer(s)

### ISSUE THREAD

**Issue by jvoigts** [open-ephys/onix-fmc-host#3]
In one specific computer, there seems to be a low-level hardware failure that can be replicated in the C program.
The computer is a pretty beefy puget systems machine, shouldn't have any intrinsic issues with power etc. The machine is also spec'd for 2 big GPUs and I replicated the issue with one GPU removed.

Steps taken to replicate:
- Use FMC host in specific PC, no external hardware needs to be connected.
- Turn on a analog io stream in bonsai (or in console app?) (could be anything but this seems to work to generate some load)
- Run the liboni-test program, set print frequency to 100.000 ( 'D' '100000'), then turn on logging ('d')
- Wait for updates to stop 😢 
- If using a firmware that outputs memory usage on the FMC, read dev_idx 10, reg_addr 4, to see if memory usage keeps going up ('r' '10 4'), In my case the value keeps going up.

In another, much lower spec, PC the same FMC with the same drivers etc. ran for 2 days without issues 🤷. 

Next steps: try another FMC board in the puget systems PC to see if it's a specific interaction of that FMC and that PC.

Hypotheses so far: power instability on PCIe? This would likely be a numato related issue?

**Comment by jonnew** [comment]
I think this was because the PXI power supply was not plugged into the PCIe board, causing power instability. Closing for now. Feel free to re-open if issue is still a concern.
